# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZ-3ab9nAgWivKDm3eOzRLVJuMzvZZOP
"""

(x,y) = map(str, input().split())

x = int(x)
y = float(y)

if x%5==0 and x+0.5<=y:
  print(y-x-0.5)

else:
  print(y)

