# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZ-3ab9nAgWivKDm3eOzRLVJuMzvZZOP
"""

N = int(input())

for i in range(N):

  a, b = map(int, input().split(' '))
  sum = a+b
  print(sum)

