# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jZ-3ab9nAgWivKDm3eOzRLVJuMzvZZOP
"""

# Take input for number of testcases
N = int(input())

for i in range(N):
    
    # Input for testcase
    num = input()
    sum = 0

    # Calculate sum and display
    for j in num:
        sum = sum + int(j)
    print(sum)

